import { PDFDocument, rgb, StandardFonts, type RGB } from "pdf-lib";

export type ColorSpec = {
  name: string;
  hex: string;
  pantone?: string;
  cmyk?: { c: number; m: number; y: number; k: number };
};

export type TechPackData = {
  projectName: string;
  date: string;
  designer?: string;
  garmentType?: string;
  printMethod?: string;
  placement?: string;
  dimensions?: string;
  colorCount?: number;
  colors: ColorSpec[];
  notes?: string;
  designImageBase64?: string;
  mockupImageBase64?: string;
};

export type RfqData = {
  companyName: string;
  contactEmail: string;
  projectName: string;
  garmentType: string;
  quantity: number;
  printMethod: string;
  colors: number;
  dimensions: string;
  deliveryDate: string;
  notes: string;
};

function hexToRgb(hex: string): RGB {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.slice(0, 2), 16) / 255;
  const g = parseInt(clean.slice(2, 4), 16) / 255;
  const b = parseInt(clean.slice(4, 6), 16) / 255;
  return rgb(r || 0, g || 0, b || 0);
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    if ((current + " " + w).trim().length <= maxChars) {
      current = (current + " " + w).trim();
    } else {
      if (current) lines.push(current);
      current = w;
    }
  }
  if (current) lines.push(current);
  return lines;
}

const DEFAULT_PAGE_ORDER = ["cover", "colors", "specs", "mockup", "notes"] as const;
type PageId = typeof DEFAULT_PAGE_ORDER[number];

export async function generateTechPackPdf(data: TechPackData, pageOrder?: PageId[]): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const W = 595, H = 842; // A4
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.05, 0.05, 0.05);
  const mid = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.08, 0.74, 0.40); // studio green

  type Ctx = {
    doc: typeof doc; W: number; H: number;
    helvetica: ReturnType<typeof doc.embedFont> extends Promise<infer T> ? T : never;
    helveticaBold: ReturnType<typeof doc.embedFont> extends Promise<infer T> ? T : never;
    black: RGB; mid: RGB; accent: RGB;
  };

  // ── Page renderers (each mutates doc by adding a page) ─────────────────────
  async function renderCover(ctx: Ctx) {
    const { doc: d, W: w, H: h, helvetica: hv, helveticaBold: hvb, black: blk, mid: mg, accent: ac } = ctx;
    const page = d.addPage([w, h]);
    page.drawRectangle({ x: 0, y: h - 80, width: w, height: 80, color: rgb(0.06, 0.06, 0.08) });
    page.drawText("DESIGN.Studio", { x: 30, y: h - 50, size: 22, font: hvb, color: rgb(1, 1, 1) });
    page.drawText("TECH PACK", { x: 30, y: h - 68, size: 11, font: hv, color: ac });
    if (data.designImageBase64) {
      try {
        const imgD = data.designImageBase64.includes(",") ? data.designImageBase64.split(",")[1] : data.designImageBase64;
        const isPng = data.designImageBase64.includes("image/png");
        const img = isPng ? await d.embedPng(Buffer.from(imgD, "base64")) : await d.embedJpg(Buffer.from(imgD, "base64"));
        const { width: iw, height: ih } = img.scale(1);
        const scale = Math.min(220 / iw, 220 / ih);
        page.drawImage(img, { x: 30, y: h - 350, width: iw * scale, height: ih * scale });
      } catch { /* skip */ }
    } else {
      page.drawRectangle({ x: 30, y: h - 350, width: 220, height: 220, color: rgb(0.93, 0.93, 0.93) });
      page.drawText("No design image", { x: 80, y: h - 250, size: 10, font: hv, color: mg });
    }
    const infoX = 280, infoY = h - 120;
    const flds = [
      ["Project", data.projectName], ["Date", data.date],
      ...(data.designer ? [["Designer", data.designer]] : []),
      ...(data.garmentType ? [["Garment", data.garmentType]] : []),
      ...(data.printMethod ? [["Print Method", data.printMethod]] : []),
      ...(data.placement ? [["Placement", data.placement]] : []),
      ...(data.dimensions ? [["Print Dimensions", data.dimensions]] : []),
      ...(data.colorCount ? [["Color Count", String(data.colorCount)]] : []),
    ] as [string, string][];
    flds.forEach(([lbl, val], i) => {
      const y = infoY - i * 26;
      page.drawText(lbl.toUpperCase(), { x: infoX, y, size: 8, font: hvb, color: mg });
      page.drawText(val, { x: infoX, y: y - 12, size: 11, font: hv, color: blk });
      page.drawLine({ start: { x: infoX, y: y - 18 }, end: { x: w - 30, y: y - 18 }, thickness: 0.5, color: rgb(0.88, 0.88, 0.88) });
    });
    page.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: hv, color: mg });
  }

  async function renderColors(ctx: Ctx) {
    if (!data.colors.length) return;
    const { doc: d, W: w, H: h, helvetica: hv, helveticaBold: hvb, black: blk, mid: mg, accent: ac } = ctx;
    const page = d.addPage([w, h]);
    page.drawRectangle({ x: 0, y: h - 80, width: w, height: 80, color: rgb(0.06, 0.06, 0.08) });
    page.drawText("COLOR SPECIFICATIONS", { x: 30, y: h - 45, size: 16, font: hvb, color: rgb(1, 1, 1) });
    page.drawText(data.projectName, { x: 30, y: h - 65, size: 10, font: hv, color: ac });
    data.colors.slice(0, 10).forEach((color, i) => {
      const rowY = h - 120 - i * 62;
      page.drawRectangle({ x: 30, y: rowY, width: 50, height: 50, color: hexToRgb(color.hex), borderColor: rgb(0.8, 0.8, 0.8), borderWidth: 0.5 });
      page.drawText(color.name, { x: 95, y: rowY + 34, size: 12, font: hvb, color: blk });
      page.drawText(`HEX: ${color.hex.toUpperCase()}`, { x: 95, y: rowY + 20, size: 9, font: hv, color: mg });
      if (color.pantone) page.drawText(`Pantone: ${color.pantone}`, { x: 95, y: rowY + 8, size: 9, font: hv, color: mg });
      if (color.cmyk) {
        const { c, m, y: cy, k } = color.cmyk;
        page.drawText(`CMYK: ${c}% / ${m}% / ${cy}% / ${k}%`, { x: 230, y: rowY + 20, size: 9, font: hv, color: mg });
      }
      page.drawLine({ start: { x: 30, y: rowY - 6 }, end: { x: w - 30, y: rowY - 6 }, thickness: 0.5, color: rgb(0.9, 0.9, 0.9) });
    });
    page.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: hv, color: mg });
  }

  async function renderSpecs(ctx: Ctx) {
    const { doc: d, W: w, H: h, helvetica: hv, helveticaBold: hvb, black: blk, mid: mg, accent: ac } = ctx;
    const page = d.addPage([w, h]);
    page.drawRectangle({ x: 0, y: h - 80, width: w, height: 80, color: rgb(0.06, 0.06, 0.08) });
    page.drawText("PRINT SPECIFICATIONS", { x: 30, y: h - 45, size: 16, font: hvb, color: rgb(1, 1, 1) });
    page.drawText(data.projectName, { x: 30, y: h - 65, size: 10, font: hv, color: ac });
    const specFlds = [
      ["Print Method", data.printMethod ?? "—"], ["Garment Type", data.garmentType ?? "—"],
      ["Placement", data.placement ?? "—"], ["Print Dimensions", data.dimensions ?? "—"],
      ["Number of Colors", String(data.colorCount ?? (data.colors.length > 0 ? data.colors.length : "—"))],
    ];
    specFlds.forEach(([lbl, val], i) => {
      const y = h - 120 - i * 42;
      page.drawRectangle({ x: 30, y: y - 10, width: w - 60, height: 36, color: i % 2 === 0 ? rgb(0.97, 0.97, 0.97) : rgb(1, 1, 1) });
      page.drawText(lbl, { x: 40, y: y + 10, size: 9, font: hvb, color: mg });
      page.drawText(val, { x: 40, y: y - 2, size: 12, font: hv, color: blk });
    });
    page.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: hv, color: mg });
  }

  async function renderMockup(ctx: Ctx) {
    if (!data.mockupImageBase64) return;
    try {
      const { doc: d, W: w, H: h, helvetica: hv, helveticaBold: hvb, mid: mg, accent: ac } = ctx;
      const page = d.addPage([w, h]);
      page.drawRectangle({ x: 0, y: h - 80, width: w, height: 80, color: rgb(0.06, 0.06, 0.08) });
      page.drawText("GARMENT MOCKUP", { x: 30, y: h - 45, size: 16, font: hvb, color: rgb(1, 1, 1) });
      page.drawText(data.projectName, { x: 30, y: h - 65, size: 10, font: hv, color: ac });
      const imgD = data.mockupImageBase64.includes(",") ? data.mockupImageBase64.split(",")[1] : data.mockupImageBase64;
      const isPng = data.mockupImageBase64.includes("image/png") || !data.mockupImageBase64.includes("image/jpeg");
      const img = isPng ? await d.embedPng(Buffer.from(imgD, "base64")) : await d.embedJpg(Buffer.from(imgD, "base64"));
      const { width: mw, height: mh } = img.scale(1);
      const mScale = Math.min((w - 60) / mw, (h - 140) / mh);
      const dw = mw * mScale, dh = mh * mScale;
      page.drawImage(img, { x: (w - dw) / 2, y: (h - 80 - dh) / 2 - 20, width: dw, height: dh });
      page.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: hv, color: mg });
    } catch { /* skip embed on error */ }
  }

  async function renderNotes(ctx: Ctx) {
    if (!data.notes) return;
    const { doc: d, W: w, H: h, helvetica: hv, helveticaBold: hvb, black: blk, mid: mg, accent: ac } = ctx;
    const page = d.addPage([w, h]);
    page.drawRectangle({ x: 0, y: h - 80, width: w, height: 80, color: rgb(0.06, 0.06, 0.08) });
    page.drawText("PRODUCTION NOTES", { x: 30, y: h - 45, size: 16, font: hvb, color: rgb(1, 1, 1) });
    page.drawText(data.projectName, { x: 30, y: h - 65, size: 10, font: hv, color: ac });
    const lines = wrapText(data.notes, 90);
    lines.slice(0, 40).forEach((line, i) => {
      page.drawText(line, { x: 30, y: h - 110 - i * 18, size: 11, font: hv, color: blk });
    });
    page.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: hv, color: mg });
  }

  // ── Render pages in the requested order ────────────────────────────────────
  const ctx: Ctx = { doc, W, H, helvetica, helveticaBold, black, mid, accent };
  const order: PageId[] = pageOrder?.length ? pageOrder : [...DEFAULT_PAGE_ORDER];
  const renderers: Record<PageId, (c: Ctx) => Promise<void>> = {
    cover: renderCover, colors: renderColors, specs: renderSpecs, mockup: renderMockup, notes: renderNotes,
  };
  for (const pageId of order) {
    await renderers[pageId](ctx);
  }

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}

export async function generateRfqPdf(data: RfqData): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const W = 595, H = 842;
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.05, 0.05, 0.05);
  const mid = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.08, 0.74, 0.40);

  const page = doc.addPage([W, H]);

  // Header
  page.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
  page.drawText("REQUEST FOR QUOTATION", { x: 30, y: H - 45, size: 18, font: helveticaBold, color: rgb(1, 1, 1) });
  page.drawText("DESIGN.Studio", { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

  // From block
  page.drawText("FROM", { x: 30, y: H - 110, size: 9, font: helveticaBold, color: mid });
  page.drawText(data.companyName, { x: 30, y: H - 125, size: 13, font: helveticaBold, color: black });
  page.drawText(data.contactEmail, { x: 30, y: H - 142, size: 10, font: helvetica, color: mid });

  // Section divider
  page.drawLine({ start: { x: 30, y: H - 155 }, end: { x: W - 30, y: H - 155 }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });

  // RFQ fields
  const rfqFields = [
    ["Project Name", data.projectName],
    ["Garment Type", data.garmentType],
    ["Print Method", data.printMethod],
    ["Quantity Required", `${data.quantity} units`],
    ["Number of Colors", `${data.colors} color${data.colors !== 1 ? "s" : ""}`],
    ["Print Dimensions", data.dimensions],
    ["Required Delivery", data.deliveryDate],
  ];

  rfqFields.forEach(([label, value], i) => {
    const y = H - 185 - i * 40;
    page.drawRectangle({ x: 30, y: y - 8, width: W - 60, height: 34, color: i % 2 === 0 ? rgb(0.97, 0.97, 0.97) : rgb(1, 1, 1) });
    page.drawText(label.toUpperCase(), { x: 38, y: y + 14, size: 8, font: helveticaBold, color: mid });
    page.drawText(value, { x: 38, y: y + 2, size: 12, font: helvetica, color: black });
  });

  // Notes
  if (data.notes) {
    const notesY = H - 185 - rfqFields.length * 40 - 20;
    page.drawText("ADDITIONAL NOTES", { x: 30, y: notesY, size: 9, font: helveticaBold, color: mid });
    const noteLines = wrapText(data.notes, 88);
    noteLines.slice(0, 15).forEach((line, i) => {
      page.drawText(line, { x: 30, y: notesY - 16 - i * 16, size: 10, font: helvetica, color: black });
    });
  }

  // Footer
  page.drawLine({ start: { x: 30, y: 50 }, end: { x: W - 30, y: 50 }, thickness: 0.5, color: rgb(0.88, 0.88, 0.88) });
  page.drawText("This RFQ was generated by DESIGN.Studio. All specifications are subject to confirmation.", { x: 30, y: 30, size: 8, font: helvetica, color: mid });
  page.drawText(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), { x: 30, y: 18, size: 8, font: helvetica, color: mid });

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}
