import { PDFDocument, rgb, StandardFonts, type RGB } from "pdf-lib";

export type ColorSpec = {
  name: string;
  hex: string;
  pantone?: string;
  cmyk?: { c: number; m: number; y: number; k: number };
};

export type TechPackData = {
  projectName: string;
  date: string;
  designer?: string;
  garmentType?: string;
  printMethod?: string;
  placement?: string;
  dimensions?: string;
  colorCount?: number;
  colors: ColorSpec[];
  notes?: string;
  designImageBase64?: string;
  mockupImageBase64?: string;
};

export type RfqData = {
  companyName: string;
  contactEmail: string;
  projectName: string;
  garmentType: string;
  quantity: number;
  printMethod: string;
  colors: number;
  dimensions: string;
  deliveryDate: string;
  notes: string;
};

function hexToRgb(hex: string): RGB {
  const clean = hex.replace("#", "");
  const r = parseInt(clean.slice(0, 2), 16) / 255;
  const g = parseInt(clean.slice(2, 4), 16) / 255;
  const b = parseInt(clean.slice(4, 6), 16) / 255;
  return rgb(r || 0, g || 0, b || 0);
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    if ((current + " " + w).trim().length <= maxChars) {
      current = (current + " " + w).trim();
    } else {
      if (current) lines.push(current);
      current = w;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export async function generateTechPackPdf(data: TechPackData): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const W = 595, H = 842; // A4
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.05, 0.05, 0.05);
  const mid = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.08, 0.74, 0.40); // studio green

  // ── Page 1: Cover ──────────────────────────────────────────────────────────
  const cover = doc.addPage([W, H]);

  // Header band
  cover.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
  cover.drawText("DESIGN.Studio", { x: 30, y: H - 50, size: 22, font: helveticaBold, color: rgb(1, 1, 1) });
  cover.drawText("TECH PACK", { x: 30, y: H - 68, size: 11, font: helvetica, color: accent });

  // Design image placeholder / embed
  if (data.designImageBase64) {
    try {
      const imgData = data.designImageBase64.includes(",")
        ? data.designImageBase64.split(",")[1]
        : data.designImageBase64;
      const isPng = data.designImageBase64.includes("image/png");
      const img = isPng
        ? await doc.embedPng(Buffer.from(imgData, "base64"))
        : await doc.embedJpg(Buffer.from(imgData, "base64"));
      const { width: iw, height: ih } = img.scale(1);
      const maxW = 220, maxH = 220;
      const scale = Math.min(maxW / iw, maxH / ih);
      cover.drawImage(img, { x: 30, y: H - 350, width: iw * scale, height: ih * scale });
    } catch { /* skip embed on error */ }
  } else {
    cover.drawRectangle({ x: 30, y: H - 350, width: 220, height: 220, color: rgb(0.93, 0.93, 0.93) });
    cover.drawText("No design image", { x: 80, y: H - 250, size: 10, font: helvetica, color: mid });
  }

  // Project info block
  const infoX = 280, infoY = H - 120;
  const fields = [
    ["Project", data.projectName],
    ["Date", data.date],
    ...(data.designer ? [["Designer", data.designer]] : []),
    ...(data.garmentType ? [["Garment", data.garmentType]] : []),
    ...(data.printMethod ? [["Print Method", data.printMethod]] : []),
    ...(data.placement ? [["Placement", data.placement]] : []),
    ...(data.dimensions ? [["Print Dimensions", data.dimensions]] : []),
    ...(data.colorCount ? [["Color Count", String(data.colorCount)]] : []),
  ] as [string, string][];

  fields.forEach(([label, value], i) => {
    const y = infoY - i * 26;
    cover.drawText(label.toUpperCase(), { x: infoX, y, size: 8, font: helveticaBold, color: mid });
    cover.drawText(value, { x: infoX, y: y - 12, size: 11, font: helvetica, color: black });
    cover.drawLine({ start: { x: infoX, y: y - 18 }, end: { x: W - 30, y: y - 18 }, thickness: 0.5, color: rgb(0.88, 0.88, 0.88) });
  });

  // Footer
  cover.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: helvetica, color: mid });

  // ── Page 2: Color Spec ─────────────────────────────────────────────────────
  if (data.colors.length > 0) {
    const colorPage = doc.addPage([W, H]);
    colorPage.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
    colorPage.drawText("COLOR SPECIFICATIONS", { x: 30, y: H - 45, size: 16, font: helveticaBold, color: rgb(1, 1, 1) });
    colorPage.drawText(data.projectName, { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

    data.colors.slice(0, 10).forEach((color, i) => {
      const rowY = H - 120 - i * 62;
      colorPage.drawRectangle({ x: 30, y: rowY, width: 50, height: 50, color: hexToRgb(color.hex), borderColor: rgb(0.8, 0.8, 0.8), borderWidth: 0.5 });
      colorPage.drawText(color.name, { x: 95, y: rowY + 34, size: 12, font: helveticaBold, color: black });
      colorPage.drawText(`HEX: ${color.hex.toUpperCase()}`, { x: 95, y: rowY + 20, size: 9, font: helvetica, color: mid });
      if (color.pantone) colorPage.drawText(`Pantone: ${color.pantone}`, { x: 95, y: rowY + 8, size: 9, font: helvetica, color: mid });
      if (color.cmyk) {
        const { c, m, y: cy, k } = color.cmyk;
        colorPage.drawText(`CMYK: ${c}% / ${m}% / ${cy}% / ${k}%`, { x: 230, y: rowY + 20, size: 9, font: helvetica, color: mid });
      }
      colorPage.drawLine({ start: { x: 30, y: rowY - 6 }, end: { x: W - 30, y: rowY - 6 }, thickness: 0.5, color: rgb(0.9, 0.9, 0.9) });
    });
    colorPage.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: helvetica, color: mid });
  }

  // ── Page 3: Print Spec ─────────────────────────────────────────────────────
  const specPage = doc.addPage([W, H]);
  specPage.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
  specPage.drawText("PRINT SPECIFICATIONS", { x: 30, y: H - 45, size: 16, font: helveticaBold, color: rgb(1, 1, 1) });
  specPage.drawText(data.projectName, { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

  const specFields = [
    ["Print Method", data.printMethod ?? "—"],
    ["Garment Type", data.garmentType ?? "—"],
    ["Placement", data.placement ?? "—"],
    ["Print Dimensions", data.dimensions ?? "—"],
    ["Number of Colors", String(data.colorCount ?? (data.colors.length > 0 ? data.colors.length : "—"))],
  ];
  specFields.forEach(([label, value], i) => {
    const y = H - 120 - i * 42;
    specPage.drawRectangle({ x: 30, y: y - 10, width: W - 60, height: 36, color: i % 2 === 0 ? rgb(0.97, 0.97, 0.97) : rgb(1, 1, 1) });
    specPage.drawText(label, { x: 40, y: y + 10, size: 9, font: helveticaBold, color: mid });
    specPage.drawText(value, { x: 40, y: y - 2, size: 12, font: helvetica, color: black });
  });
  specPage.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: helvetica, color: mid });

  // ── Page 4: Mockup / Garment Preview ──────────────────────────────────────
  if (data.mockupImageBase64) {
    try {
      const mockupPage = doc.addPage([W, H]);
      mockupPage.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
      mockupPage.drawText("GARMENT MOCKUP", { x: 30, y: H - 45, size: 16, font: helveticaBold, color: rgb(1, 1, 1) });
      mockupPage.drawText(data.projectName, { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

      const imgData = data.mockupImageBase64.includes(",")
        ? data.mockupImageBase64.split(",")[1]
        : data.mockupImageBase64;
      const isPng = data.mockupImageBase64.includes("image/png") || !data.mockupImageBase64.includes("image/jpeg");
      const mockupImg = isPng
        ? await doc.embedPng(Buffer.from(imgData, "base64"))
        : await doc.embedJpg(Buffer.from(imgData, "base64"));
      const { width: mw, height: mh } = mockupImg.scale(1);
      const maxMW = W - 60, maxMH = H - 140;
      const mScale = Math.min(maxMW / mw, maxMH / mh);
      const drawW = mw * mScale, drawH = mh * mScale;
      mockupPage.drawImage(mockupImg, {
        x: (W - drawW) / 2,
        y: (H - 80 - drawH) / 2 - 20,
        width: drawW,
        height: drawH,
      });
      mockupPage.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: helvetica, color: mid });
    } catch { /* skip embed on error */ }
  }

  // ── Page 5: Production Notes ───────────────────────────────────────────────
  if (data.notes) {
    const notesPage = doc.addPage([W, H]);
    notesPage.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
    notesPage.drawText("PRODUCTION NOTES", { x: 30, y: H - 45, size: 16, font: helveticaBold, color: rgb(1, 1, 1) });
    notesPage.drawText(data.projectName, { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

    const lines = wrapText(data.notes, 90);
    lines.slice(0, 40).forEach((line, i) => {
      notesPage.drawText(line, { x: 30, y: H - 110 - i * 18, size: 11, font: helvetica, color: black });
    });
    notesPage.drawText(`Generated by DESIGN.Studio · ${data.date}`, { x: 30, y: 20, size: 8, font: helvetica, color: mid });
  }

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}

export async function generateRfqPdf(data: RfqData): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const W = 595, H = 842;
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const black = rgb(0.05, 0.05, 0.05);
  const mid = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.08, 0.74, 0.40);

  const page = doc.addPage([W, H]);

  // Header
  page.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: rgb(0.06, 0.06, 0.08) });
  page.drawText("REQUEST FOR QUOTATION", { x: 30, y: H - 45, size: 18, font: helveticaBold, color: rgb(1, 1, 1) });
  page.drawText("DESIGN.Studio", { x: 30, y: H - 65, size: 10, font: helvetica, color: accent });

  // From block
  page.drawText("FROM", { x: 30, y: H - 110, size: 9, font: helveticaBold, color: mid });
  page.drawText(data.companyName, { x: 30, y: H - 125, size: 13, font: helveticaBold, color: black });
  page.drawText(data.contactEmail, { x: 30, y: H - 142, size: 10, font: helvetica, color: mid });

  // Section divider
  page.drawLine({ start: { x: 30, y: H - 155 }, end: { x: W - 30, y: H - 155 }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });

  // RFQ fields
  const rfqFields = [
    ["Project Name", data.projectName],
    ["Garment Type", data.garmentType],
    ["Print Method", data.printMethod],
    ["Quantity Required", `${data.quantity} units`],
    ["Number of Colors", `${data.colors} color${data.colors !== 1 ? "s" : ""}`],
    ["Print Dimensions", data.dimensions],
    ["Required Delivery", data.deliveryDate],
  ];

  rfqFields.forEach(([label, value], i) => {
    const y = H - 185 - i * 40;
    page.drawRectangle({ x: 30, y: y - 8, width: W - 60, height: 34, color: i % 2 === 0 ? rgb(0.97, 0.97, 0.97) : rgb(1, 1, 1) });
    page.drawText(label.toUpperCase(), { x: 38, y: y + 14, size: 8, font: helveticaBold, color: mid });
    page.drawText(value, { x: 38, y: y + 2, size: 12, font: helvetica, color: black });
  });

  // Notes
  if (data.notes) {
    const notesY = H - 185 - rfqFields.length * 40 - 20;
    page.drawText("ADDITIONAL NOTES", { x: 30, y: notesY, size: 9, font: helveticaBold, color: mid });
    const noteLines = wrapText(data.notes, 88);
    noteLines.slice(0, 15).forEach((line, i) => {
      page.drawText(line, { x: 30, y: notesY - 16 - i * 16, size: 10, font: helvetica, color: black });
    });
  }

  // Footer
  page.drawLine({ start: { x: 30, y: 50 }, end: { x: W - 30, y: 50 }, thickness: 0.5, color: rgb(0.88, 0.88, 0.88) });
  page.drawText("This RFQ was generated by DESIGN.Studio. All specifications are subject to confirmation.", { x: 30, y: 30, size: 8, font: helvetica, color: mid });
  page.drawText(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), { x: 30, y: 18, size: 8, font: helvetica, color: mid });

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}
